import Layout from "@/components/layout/Layout";
import "./globals.css";
import {yekanBakh} from "@/utils/fonts";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({children}) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${yekanBakh.className} bg-background`}>
        <Layout className={yekanBakh.className}>{children}</Layout>
      </body>
    </html>
  );
}
